### ISSUE TITLE
How can i know the data which i want to share is scanned by other Device?

### ISSUE THREAD

**Issue by shashi-kiwi** [appidea/react-native-hce#1]
Hi,
 I start simulation and data is scanned by other device but How can i get to know that the other device has scanned?
Thanks in Advance . Please answer asap.
Thanks,
Shashi

**Comment by spsingh559** [comment]
I am having a similar question. Can we implement HCE reader in react native? All I can see is Emulating an NFC Card using React native but what about the reader app which can read emulated device?

My use case is to send a personal identifiable information data from one app to other in different mobile phones with NFC enabled. It would be great to see if any peer-to-peer data sharing using NFC example is there.

**Comment by appidea** [comment]
You probably need to use this library combined with react-native-nfc-manager to reach this kind of functionality

**Comment by SurpriseMF3000** [comment]
Any new method?
