### ISSUE TITLE
listen() function isseus

### ISSUE THREAD

**Issue by SurpriseMF3000** [appidea/react-native-hce#20]
Hello again;)
im facing issues with the listen() function.
If im calling the `listen()` function in the `startsession()` function, the phone recognizes when there is an actual data transfer and everything works the first time great.
But when im calling the `startsession()` function a second time, the `listen()` output from the first time gets printed and fucks everything up.

Is there any way to avoid this?

Thanks for Help!

**Comment by SurpriseMF3000** [comment]
I figured out that the only way to avoid this is to set `session.on = null;` after a full cycle before the next one.

Are there any other ways?

**Comment by appidea** [comment]
Did You try to cleanup previous event listeners before creating the new session?
To do that, call the function that comes as a result of `on(...)` method.

**Comment by appidea** [comment]
no response, closing...
