### ISSUE TITLE
How to compile Java code

### ISSUE THREAD

**Issue by camo-f** [appidea/react-native-hce#21]
Hello,

I'm trying to apply modifications to the Java code of react-native-hce.
My goal is to make it more flexible to use (configuring AID for instance).
Though I can't get to rebuild the Java part, either as a dependency in a React Native app, or as a standalone repository.

Could you provide some documentation to enable Java compiling as a subproject or as a whole please?

Thank you!

**Comment by appidea** [comment]
Sorry, cannot understand the problem. Do You experience some error when trying to rebuild? Can You drop it here?
