### ISSUE TITLE
NFC Permissions

### ISSUE THREAD

**Issue by 0xcD3v** [appidea/react-native-hce#28]
How can we force android to ask user permissions to acess NFC module?

Am emulating a tag, and i only start the emulation process when user clicks on a button but if the user doesn't have the nfc turned on, the aplication doesn't ask for permissions.
I already looked up react native documentation but i didn't found a permission for NFC.

**Comment by appidea** [comment]
Just googled about Your problem and found a SO topic which could be some kind of clue:
https://stackoverflow.com/questions/7618657/how-to-check-whether-nfc-is-enabled-or-not-in-android
