### ISSUE TITLE
React-native-hce. Build failed

### ISSUE THREAD

**Issue by NobeliY** [appidea/react-native-hce#33]
Sorry for my english.
Failure: build failed with an exception.
I'm try use example, but program drop exception with creating task.
Error message:
`
FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':react-native-hce'.
> Failed to notify project evaluation listener.
   > Could not create task ':react-native-hce:compileDebugAndroidTestKotlin'.
      > Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
   > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.
 Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
BUILD FAILED in 4s
error Failed to install the app.
`

**Comment by appidea** [comment]
Plz check #29, seems that can be related with Your issue
